kind: PersistentVolume
apiVersion: v1
metadata:
    name: my-pv
spec:
    capacity:
      storage: 20Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: my-storage-class
    hostPath:
      path: /your/host/path
