kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: my-pvc
spec:
    volumeName: my-pv
    storageClassName: my-storage-class
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
